### PR TITLE
upd765 optimization + Pentagon1024

### PR DESCRIPTION
**Pull request by gyurco**
Hi!

There were some patches in my tree, so I decided to create this PR. I think you can use them for MiSTer, too, if you want.

### CODE REVIEW

**Comment by sorgelig** [comment]
Thanks for patches!
I've used Pentagon 512K because it's highest memory size backward compatible with Pentagon 128K paging model. 
Ok. Let's switch to Pentagon 1024K.

**Comment by gyurco** [comment]
Thanks for merging!
I've just found this Robocop 1024k remix, and wanted to make it work. I never used anything Pentagon 512k specific, hope the patch won't break anything.

**Comment by gyurco** [comment]
Well, I'm almost sure that 48k mode will not disable paging now, because now bit2 in #effd should be set to 1 first.
So for a real 48k mode:
OUT 61431,4
OUT 32765,48

**Comment by gyurco** [comment]
Yepp, confirmed with JetPac/keyboard mode, 48k mode doesn't disable paging. Maybe the ROM was modified in the real Pentagon 1024.

**Comment by sorgelig** [comment]
Pentagon 1024 had its own ROM as far as i remember. 
Since we have a separate Pentagon 128K, it's OK.

**Pull request merged**
