### PR TITLE
Fix double side disks in upd765.

### PR DESCRIPTION
**Pull request by gyurco**
Hello! Another patch for handling DS disks correctly.

What would be needed for a new MiST release?

### CODE REVIEW

**Comment by sorgelig** [comment]
Did you fix metastability problem?

**Comment by gyurco** [comment]
My local repo is just same as yours now, and it is stable.

**Comment by sorgelig** [comment]
released

**Comment by gyurco** [comment]
Great! Thank you, just tested it and works well.

**Pull request merged**
