### PR TITLE
Don't disable the ULA port write during turbo loading

### PR DESCRIPTION
**Pull request by gyurco**

### CODE REVIEW

**Comment by sorgelig** [comment]
This pull is unnecessary and too obvious. I've already did this quickfix.

**Comment by gyurco** [comment]
Of course, it is obvious. But was a great conversation discovering the problem, and helped me to understand your code (and your intentions, because the harder task is to found out why a piece of code is there sometimes).

**Comment by sorgelig** [comment]
I will try. I still want to disable writing first. Just need to find some time between other projects.

**Comment by sorgelig** [comment]
By the way, my current development platform is MiSTer: https://github.com/MiSTer-devel/Main_MiSTer/wiki
ZX core is ported there as well.

**Comment by sorgelig** [comment]
Ok, I've tested with write disable and found that write enable works better.

**Comment by sorgelig** [comment]
pushed the commit

**Comment by gyurco** [comment]
Looks great, and one can use a more recent Quartus release to develop I guess. And probably cheaper than Mist? Just curious, why just 3x6 bit VGA, and not 3x8? Not enough pins?

**Comment by sorgelig** [comment]
Main video output is HDMI which is 24bit.
VGA is mostly for debugging. 99% of cores don't need more than 18bit. 80% don't need even 12bits.
There is no reason to waste the GPIO. Doing 24bits for VGA will require DAC chip (otherwise why bother?) which will increase the cost and board assembly complexity which is considered DIY.

**Pull request closed without merging**
